# Generated by Django 5.0 on 2024-01-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
